#!/usr/bin/env python3
"""Regenerate templates/icons.html from migrate/reference/icons/*.svg.

One-off-ish tool: rerun only when adding a new icon (drop the SVG extracted
from an Iconify set into migrate/reference/icons/ as <set>--<name>.svg).
Markup replicates astro-icon's rendered output; see the header comment it
writes. The brew_type_icon dispatcher at the bottom is maintained here too.
"""
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
out = ['''{# Inline-SVG icon components — generated by migrate/gen-icons.py from
   migrate/reference/icons/ (extracted from the Astro @iconify-json sets).
   Markup replicates astro-icon's rendered output exactly:
   <svg width=<aspect>em height=1em data-icon><symbol viewBox>body</symbol><use/></svg>
   — the CSS targets [data-icon="set:name"] selectors. Loading this file
   registers the components globally; it is never rendered directly. #}
''']
for svg_path in sorted((ROOT / "migrate/reference/icons").glob("*.svg")):
    set_name, icon = svg_path.stem.split("--", 1)
    svg = svg_path.read_text().strip()
    viewbox = re.search(r'viewBox="([^"]+)"', svg).group(1)
    body = re.sub(r"^<svg[^>]*>|</svg>$", "", svg)
    iconify = f"{set_name}:{icon}"
    comp = "icon_" + f"{set_name}_{icon}".replace("-", "_")
    # astro-icon sets width from the viewBox aspect ratio, ceiled to 2dp
    # (baseline: fontisto:podcast 20/24 -> 0.84em, ps:rss 464/488 ->
    # 0.96em, fa-solid:coffee 640/512 -> 1.25em, square -> 1em).
    _, _, vw, vh = (float(x) for x in viewbox.split())
    width = math.ceil(vw / vh * 100) / 100
    width_attr = "1em" if width == 1 else f"{width:g}em"
    out.append(
        f'{{% component {comp}(id = "") %}}'
        f'<svg width="{width_attr}" height="1em"{{% if id %}} id="{{{{ id }}}}"{{% endif %}} data-icon="{iconify}">'
        f'<symbol id="ai:{iconify}" viewBox="{viewbox}">{body}</symbol>'
        f'<use href="#ai:{iconify}"></use></svg>'
        f'{{% endcomponent {comp} %}}\n'
    )
out.append('''{# brewIcon() port (stringformatter.mjs): dynamic icon by brew type. #}
{% component brew_type_icon(type = "beer") %}{% if type == "tea" %}{{<icon_mdi_tea />}}{% elif type == "coffee" %}{{<icon_fa_solid_coffee />}}{% elif type == "water" %}{{<icon_ion_waterdrop />}}{% else %}{{<icon_ion_beer />}}{% endif %}{% endcomponent brew_type_icon %}
''')
(ROOT / "templates/icons.html").write_text("\n".join(out))
print(f"icons.html: {len(out) - 2} icon components")
